theme: jekyll-theme-slate
title: [ゼロからのOS自作入門 サポートサイト](https://zero.osdev.jp/)
description: 「ゼロからのOS自作入門」（内田公太著、マイナビ出版）のサポートサイトです。書籍の内容に関する質疑応答、正誤表の提供、読者同士のコミュニケーションを主な目的としています。
show_downloads: false
